### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by mmaenz** [ostr00000/freecad-stubs#1]
Hi,

thanks for all your work, this is great and I was looking a long time for something like this. And sorry for creating an issue, I didn't know how to reach you.

I have a question regarding an import error message and intellisense. 
![image](https://user-images.githubusercontent.com/22559887/153633963-ad1020c9-39b1-4fe1-9ed7-db77fb533157.png)
I read that this kind of error occures when no library and only definition is found? ([Issue here](https://github.com/microsoft/pylance-release/issues/2158)).

But I would expect that intellisense should find the package when typing?
![image](https://user-images.githubusercontent.com/22559887/153634404-f1035138-e7ed-485c-a807-b20645e47fe9.png)

Or do I misunderstand something here?

Thanks!

**Comment by ostr00000** [comment]
Hi, I have never used Pylance, but it seems that some FreeCAD modules are not available in your python search path. 


### Explanation
When FreeCAD program starts, there is some path manipulation. If you type in FreeCAD in Python console:
```python
import sys
sys.path
```
then you see that there are many paths to search for modules.
For example, here are some paths for FreeCAD 0.18 in linux:
```python
['/usr/share/freecad/Mod/MeshPart', '/usr/share/freecad/Mod/Part', '/usr/share/freecad/Mod/PartDesign', ...]
```
On the other hand, if you run python from console and type the same expression, then probably you will not see any of these paths. Moreover, if you will try to `import FreeCAD` or any other FreeCAD module (ex. `Part`), then you got `ModuleNotFoundError`. (I am not sure why `FreeCAD` and `FreeCADGui` do not have this error)

As you pointed `this kind of error occures when no library and only definition is found` may be true, because `freecad-stubs` are installed in normal python packages location, whereas FreeCAD packages are outside these standard paths.

### Solution
1. One solution is to configure your IDE appropriately:
    - in case of Pylance you may look for something like [`extraPaths`](https://github.com/microsoft/pylance-release/issues/29#issuecomment-653053357).
    - in case of PyCharm [this](https://stackoverflow.com/questions/17198319/how-to-configure-custom-pythonpath-with-vm-and-pycharm) question may be helpful.

2. But sometimes it is cumbersome (we must add a lot of paths), so one can use another solution - add all required paths to special file `freecad_paths.pth` (file name may be arbitrary, but the extension is important - [python docs](https://docs.python.org/3/library/site.html)). The file should be placed somewhere in folder `site-packages` - the exact location depends on how you use python (system interpreter, venv). This is my file: 
	  <details>
	  <summary>freecad_paths.pth</summary>
	  <p>
	  
	  ```bash
	  /usr/share/freecad/Mod/Inspection
	  /usr/share/freecad/Mod/Robot
	  /usr/share/freecad/Mod/Drawing
	  /usr/share/freecad/Mod/ReverseEngineering
	  /usr/share/freecad/Mod/Arch
	  /usr/share/freecad/Mod/Draft
	  /usr/share/freecad/Mod/Image
	  /usr/share/freecad/Mod/Sketcher
	  /usr/share/freecad/Mod/Web
	  /usr/share/freecad/Mod/Fem
	  /usr/share/freecad/Mod/Spreadsheet
	  /usr/share/freecad/Mod/Test
	  /usr/share/freecad/Mod/MeshPart
	  /usr/share/freecad/Mod/Tux
	  /usr/share/freecad/Mod/Path
	  /usr/share/freecad/Mod/Measure
	  /usr/share/freecad/Mod/Start
	  /usr/share/freecad/Mod/Surface
	  /usr/share/freecad/Mod/Points
	  /usr/share/freecad/Mod/Import
	  /usr/share/freecad/Mod/Show
	  /usr/share/freecad/Mod/Idf
	  /usr/share/freecad/Mod/Part
	  /usr/share/freecad/Mod/Mesh
	  /usr/share/freecad/Mod/TechDraw
	  /usr/share/freecad/Mod/AddonManager
	  /usr/share/freecad/Mod/Material
	  /usr/share/freecad/Mod/Raytracing
	  /usr/share/freecad/Mod/OpenSCAD
	  /usr/share/freecad/Mod/PartDesign
	  /usr/lib/freecad-python3/lib
	  /usr/share/freecad/Ext
	  ```
	  
	  </p>
	  </details>
	  If you have custom modules, you may add them here too. 

3. Yet another solution is to configure `PYTHONPATH` environment variable (But I am afraid that this solution may be too tricky for most IDE). Anyway, this is example how to run your python script that use FreeCAD modules without starting whole FreeCAD. The module is actually subpackage of package `freecad` ([alternative workbench structure](https://github.com/FreeCAD/freecad.workbench_starterkit/)).
```bash
function join() {
  local IFS=$1
  shift
  echo "$*"
}
PYTHONPATH="/usr/lib/freecad-python3/lib/:/usr/share/freecad/Ext/:$(join ':' /usr/share/freecad/Mod/*):$PYTHONPATH" python3 -m freecad.script_updater
```

I hope that this will help you, because I remember that also I had a lot of problems with IDE configuration for FreeCAD. If there will be issues with stubs, please let me know.

**Comment by mmaenz** [comment]
Thank you for this extended answer. This was very helpful to understand. Your were right, I did not included the paths the wrong way. I figured out that your freecad-stubs is available on pip, did install that instead of cloning the repo. No need to adjust paths to external stubs/interfaces. No problems with the stubs so far.

But I'm quite interested in whats your way of developing for freecad? Your probably using PyCharm? How do you debug workbenches successful and what about reloading? I'm currently using importlib.reload to not restart freecad everytime.

Visual Studio and VSCode use exactly the same technique (pylance and debugpy) under the hood except that the big brother has a nicer gui. I ended up using that.

Do you have any further advice?

**Comment by ostr00000** [comment]
Yes, I use PyCharm. I have problems to achieve easy debug tool, because I need to use [remote debug](https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config) which is only available in PyCharm Professional version (paid version). Fortunately, at this moment there is [Early Access Program](https://www.jetbrains.com/pycharm/nextversion/), so I tested it now, and it works really well.

Previously, guided by this [post](https://forum.freecadweb.org/viewtopic.php?t=35383) and [wiki](https://wiki.freecadweb.org/Debugging#Python_Debugging), I used [winpdb](https://pypi.org/project/winpdb-reborn), but it is much less convenient than PyCharm. There is also [PyDev](https://www.pydev.org/manual_adv_remote_debugger.html) with similar debug possibilities as PyCharm (If I remember correctly, PyCharm remote debugger was a fork of PyDev, and later they merged).

I do not know which version of FreeCAD you use, but I see that in FreeCAD 0.19 in `Macro` menu is a new action `Attach to remote debugger`. There are two possible debuggers: winpdb and VC Code, so you may be interested in.

I was thinking about reloading, but finally I give up. In my case, I would have to reload most of the Proxy classes (and somehow their objects). Very often the changes were in code that create/load object (Almost all my objects in FreeCAD were actually part of greater system with Postgres DB). I am also not sure how the internal C code will work with such changes.

Probably it may not be possible (there may be missing functions for Python), but I would advise you to write two functions: `load` and `unload` for each your workbench. Then you can easily reload each workbench separately without restarting the whole application (but then again, it may not be so simple/possible if one mod depends on another).
