### ISSUE TITLE
missing: src/Gui/SelectionObserverPython.h

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [ostr00000/freecad-stubs#11]
`SelectionObserverPython` has no `xml` and so it is missing from the stubs:

https://forum.freecad.org/viewtopic.php?p=497885

https://github.com/FreeCAD/FreeCAD/blob/1e212c32bc8ddf13443c1d61c1e403a9c5d6a5b6/src/Gui/SelectionObserverPython.h#L64

```cpp
#define FC_PY_SEL_OBSERVER \
    FC_PY_ELEMENT(onSelectionChanged) \
    FC_PY_ELEMENT(addSelection) \
    FC_PY_ELEMENT(removeSelection) \
    FC_PY_ELEMENT(setSelection) \
    FC_PY_ELEMENT(clearSelection) \
    FC_PY_ELEMENT(setPreselection) \
    FC_PY_ELEMENT(removePreselection) \
    FC_PY_ELEMENT(pickedListChanged)
```

**Comment by ostr00000** [comment]
If I understood correctly my own code, this class should be written manually (it matches the same regex I used in [this file](https://github.com/ostr00000/freecad-stubs/blob/5dcafad26a620cf1265abbddbe7436410dd560d0/lib/freecad_stub_gen/FreeCADTemplates/templates.py#L14)).
This is because of extensive usage of C++ macros in FreeCAD code. 

I am going to automate this, by resolving first these macros. This is partially implemented - I can generate these files in recent commits. 
This will be heavy refactoring, so it requires some time. Maybe I will find some free time at the last week of this year.

I am going to return to this issue when https://github.com/ostr00000/freecad-stubs/issues/12 will be closed.

**Comment by ostr00000** [comment]
I decided to write this template class manually. It should be available in next release.
