### ISSUE TITLE
Pylance: wont find stubs for native library with submodules

### ISSUE THREAD

**Issue by RamilKadyrov** [ostr00000/freecad-stubs#16]
**Describe the bug**
VS code with Pylance: wont find stubs for native library with submodules.
According https://peps.python.org/pep-0484/#stub-files

>  - Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form. 

>  - Just like in [normal Python files](https://docs.python.org/3/reference/import.html#submodules), submodules automatically become exported attributes of their parent module when imported. For example, if the spam package has the following directory structure:
> 
> ```
> spam/
>     __init__.pyi
>     ham.pyi
> ```
> where `__init__.pyi` contains a line such as `from . import ham` or `from .ham import Ham`, then ham is an exported attribute of spam.

**To Reproduce**
1. FreeCAD 0.21.2 installed
2. C:\Program Files\FreeCAD 0.21\bin> python -m pip install freecad-stubs
3.  In VS Code in a new folder created test.py  file with code

```
 #!/usr/bin/env python
import sys
import FreeCAD as FreeCAD
import FreeCADGui as Gui
import Part
from PySide import QtGui

if __name__ == "__main__":
    # This will start FreeCAD and draw a box. 
    app = QtGui.QApplication(sys.argv)
    Gui.showMainWindow()
    
    doc = FreeCAD.newDocument()
    box = Part.makeBox(100, 100, 100)
    FreeCAD.Console.PrintMessage('Hello, World!')
    
        
    Part.show(box)
    sys.exit(app.exec_())
```
and .env file 

```
FREECAD_BIN="C:/Program Files/FreeCAD 0.21/bin"
FREECAD_BIN_LIB="C:/Program Files/FreeCAD 0.21/bin/Lib"
FREECAD_BIN_LIB_PAC="C:/Program Files/FreeCAD 0.21/bin/Lib/site-packages"
FREECAD_LIB="C:/Program Files/FreeCAD 0.21/lib"
FREECAD_MOD="C:/Program Files/FreeCAD 0.21/Mod"
FREECAD_EXT="C:/Program Files/FreeCAD 0.21/EXT"
PYTHONPATH=${FREECAD_BIN};${FREECAD_LIB};${FREECAD_MOD};${FREECAD_EXT};${FREECAD_BIN_LIB};${FREECAD_BIN_LIB_PAC}
```

5. If the mouse cursor hover on FreeCAD.Console.PrintMessage there is no information about the function. 

**Expected behavior**
If the mouse cursor hover on Part.makeBox there is information about the function. 

**Used versions (please complete the following information):**
 - FreeCAD version 0.21.2
 - FreeCAD-stub version 1.0.16

**Additional context**
To fix the issue I've added `from . import Console` instead of `import FreeCAD.Console` to the file `__init__.pyi` in the `C:\Program Files\FreeCAD 0.21\bin\Lib\site-packages\FreeCAD-stubs\` folder.

**Comment by ostr00000** [comment]
Sorry for no quick response, and thanks for very detailed issue report (even links to PEP and how to solve this issue!)

I had some problems with testing this in VS Code 
(Surprisingly, removing `PYTHONPATH` that points to my FreeCAD path, forced `pylance` to use stubs).

---

The issue was actually even more tricky, because you can do this:
```python
>>> from FreeCAD import Console; print(type(Console))
<class 'module'>
```
But you cannot import `Console` module directly from `FreeCAD` module:
```python
>>> import FreeCAD.Console
ModuleNotFoundError: No module named 'FreeCAD.Console'
```
This behavior is decided in C++ code.

---


Finally, I think that I fixed it and also some additional imports.
It seems to work as planned in `PyCharm`, `pyright`, but I am not sure about `pylance`.

`pylance` detect that the module exists in both cases (as showed in example, there should be an error in second one).
It may be only my wrong VS setup, or indeed an error in `pylance`. If a second case, then it may be reported in `pylance`, but probably this is not a very severe problem.
