### ISSUE TITLE
__rmul__ missing from generated functions at least in Vector.

### ISSUE THREAD

**Issue by MichaelAReed** [ostr00000/freecad-stubs#2]
This repo is great, thanks for putting it together.

While using it for the first time today, I noticed that for the Vector class in the generated stub file Base.pyi, the __mul__ magic method is included but __rmul__ is not.

This results in no mypy errors for something like:
`Vector(1,1,1) * 10`
But an error of: 'Unsupported operand types for * ("float" and "Vector")' error for:
`10 * Vector(1,1,1)`

Once I get time, I'll poke around the generation code to try and add this in or would be happy for someone else to do so.

**Comment by ostr00000** [comment]
> This repo is great

Thanks for nice words.

> the mul magic method is included but rmul is not

You are totally right. The reflected methods (with prefix `__r`) are missing in stubs.
I added these methods, and fixed some others.

Unfortunately, FreeCAD code is very complicated. Many stub methods exist in C code, but they immediately raise exceptions when called (ex. `FreeCAD.Vector(1, 2, 3) << 1`). 
I see also that some stubs are incorrect, ex. dot product return `int` instead of `Vector`, so I removed invalid stubs:
```
assert isinstance(FreeCAD.Vector(1, 2, 3) * FreeCAD.Vector(1, 2, 3), int)
```

I also added some other improvements (default values from C code).
Please confirm if the issue is solved. And thanks for this issue.
