### ISSUE TITLE
[Question] App is not defined

### ISSUE THREAD

**Issue by sdifru** [ostr00000/freecad-stubs#3]
Hi! I've just found this project and it seems like it would be very useful for people who create workbench or macro for freecad.

I'm currently writing a macro and I've installed this package. The problem is that error message from lsp such as `"App" is not defined` shows up.

I know that it is because I don't define `App` in my code. Freecad would use the `App` variable inside the program when I run the macro. But are there any way I can get rid of this error message?

Another thing is when I write `doc = App.ActiveDocument`, the `doc` type would be `Unknown`. How can I change the type into `Document`?

**Comment by ostr00000** [comment]
Hi,
I once encountered a similar problem. Although it was a different program, the problem was the same:  the program insert some variables into script namespace, then run the script.
As you noticed, FreeCAD injects some variables at runtime. Unfortunately, I have not found any satisfying solution/workaround. 

Some possibilities I was tried:
- Reassign variable in script: `injected_var = globals()['injected_var']`.
  If we want also type checks for this, variable must be annotated with appropriate type (`injected_var: int = globals()['injected_var']`).
  This workaround is very suspicious, and I do not recommend it, but it succeeded with type checker.
- Import variable explicitly (does not work if injected variable is dynamic). In your case, you can use this: `import FreeCAD as App`. Similar for other variables.
  This may be interesting: https://github.com/FreeCAD/FreeCAD/blob/2a1d4d4994bf3707f7a07aef07e17f5270b4854b/src/App/FreeCADInit.py#L296 and https://github.com/FreeCAD/FreeCAD/blob/2a1d4d4994bf3707f7a07aef07e17f5270b4854b/src/Gui/FreeCADGuiInit.py#L35 - these scripts are run by FreeCAD when python is initialized. 
  This is the solution I use in all scripts for FreeCAD (although I prefer using `FreeCAD` to `App`).

> Another thing is when I write doc = App.ActiveDocument, the doc type would be Unknown. How can I change the type into Document

If the guessed type is `Unknown/Any` you can always help in guessing by explicit annotation: `doc: Document = App.ActiveDocument` (of course you must import `Document` previously).
But the original reason for `Unknown` type for `ActiveDocument` is because of `App` is also not recognized (type check consider it as `Unknown` type).
So solving type for `App`, should solve all further problems (if not, please report me).

---

The described problem is related to insufficient IDE configuration. I have no power here (i.e. in freecad-stubs) to influence any IDE. Unfortunately, I have never seen in any IDE a possibility to influence python `builtin` by injecting custom variable. There are similar problems for tools like `mypy` (ex. https://github.com/python/mypy/issues/7931). I have not tested it, but it may be possible to configure it in pyright - https://github.com/python/mypy/issues/12172#issuecomment-1038279101.

So my final advice is to use explicit import whenever possible `Explicit is better than implicit.` (https://peps.python.org/pep-0020/#the-zen-of-python).

**Comment by sdifru** [comment]
Very comprehensive explanations, thank you @ostr00000!
