### ISSUE TITLE
Include in FreeCAD proper?

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [ostr00000/freecad-stubs#7]
Hello, and thank you for a great project.
I am curious if you considered asking  the "FreeCAD people" to include this as standard part of FreeCAD distribution?
Why? I would hope that would motivate "them" to fix multiple errors and omissions in cpp/py bridge faster :-)

**Comment by ostr00000** [comment]
Hi, 

### Advantages
I think that it would be an ideal solution to generate stubs together with compilation, because I already observed a bit of branching between my generated stubs and current C++ implementation. 
Moreover, I must actively maintain stubs (I must regenerate them manually + upload to pypy, I am not familiar with GitHub actions, so I have not automated this yet).
I would prefer to keep a generator code in a separate repo to be able to easily modify generator code. But I am fine with adding this to compilation toolchain, distributing generated stubs, or even transfer this project to FreeCAD organization.

### Disadvantages
FreeCAD has many [installation formats](https://www.freecad.org/downloads.php), but in my opinion programmers have their custom Python environment frequently managed by IDE, so in my opinion `pip` installation is the easiest option.
I am Linux user, so I am not sure about other systems, but `AppImage` format is not useful for developing at all. While developing, I used FreeCAD from debian package - probably this should be more useful to include stubs here, but currently deb distribution is not actively [maintained](https://forum.freecad.org/viewtopic.php?t=69055&start=90).

> that would motivate "them"

Currently, errors are only printed to not block the generation process. Actually, there are only few 6-8 errors, so I think I should just report an issue in FreeCAD repo.
Also, this tool "crash" frequently when updating to newer commits. It is by design - I want to catch all possible error/new types of code (that not match my regex). Most of the time, it is a very quick fix, but this would probably block all build process.

### Alternatives
If there is really a need to create a validation tool, for example for `PyArg_ParseTupleAndKeywords` (this function has variadic argument length, so this is the most frequent error, because C++ compiler does not validate this), I think it would be possible to extract few files and move to a new project with [pre-commit](https://pre-commit.com/) hook (I see FreeCAD already use pre-commit).

BTW: I plan to rewrite this tool a bit, to be more "structural", and less regex based. Recently, in C++ there is more `auto` in type declaration and lambda functions, which generate incorrect stubs (probably generation time will increase by order of magnitude, but stubs quality greatly improve). 

### Summary
- I will keep this issue open until I report all errors to FreeCAD repo. 
- I am ok with including this in FreeCAD, but this should be adopted/adjusted by FreeCAD maintainers in their toolchain.
- Maybe in the future, when the generator code become more stable, I reconsider this issue.

**Comment by Andrei-Pozolotin** [comment]
Great, thank you for thinking about this. Would it  make sense to start a conversation on this on the FreeCAD form?

**Comment by ostr00000** [comment]
I think it makes sense. After all, if FreeCAD maintainers do not want stubs included with binary files, the discussion here is pointeless. 
Could you create a thread on the forum and post a link here?
